In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('student_scores.csv')
dataset.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [9]:
x=dataset.iloc[:,:1].values
y=dataset.iloc[:,:4].values
print("x values",x)
print("y values",y)

x values [[2.5]
 [5.1]
 [3.2]
 [8.5]
 [3.5]
 [1.5]
 [9.2]
 [5.5]
 [8.3]
 [2.7]
 [7.7]
 [5.9]
 [4.5]
 [3.3]
 [1.1]
 [8.9]
 [2.5]
 [1.9]
 [6.1]
 [7.4]
 [2.7]
 [4.8]
 [3.8]
 [6.9]
 [7.8]]
y values [[ 2.5 21. ]
 [ 5.1 47. ]
 [ 3.2 27. ]
 [ 8.5 75. ]
 [ 3.5 30. ]
 [ 1.5 20. ]
 [ 9.2 88. ]
 [ 5.5 60. ]
 [ 8.3 81. ]
 [ 2.7 25. ]
 [ 7.7 85. ]
 [ 5.9 62. ]
 [ 4.5 41. ]
 [ 3.3 42. ]
 [ 1.1 17. ]
 [ 8.9 95. ]
 [ 2.5 30. ]
 [ 1.9 24. ]
 [ 6.1 67. ]
 [ 7.4 69. ]
 [ 2.7 30. ]
 [ 4.8 54. ]
 [ 3.8 35. ]
 [ 6.9 76. ]
 [ 7.8 86. ]]


In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(x_test)

[[7.4]
 [2.5]
 [5.1]
 [3.2]
 [6.1]
 [4.5]
 [7.8]
 [8.3]]


In [12]:
print(y_test)

[[ 7.4 69. ]
 [ 2.5 21. ]
 [ 5.1 47. ]
 [ 3.2 27. ]
 [ 6.1 67. ]
 [ 4.5 41. ]
 [ 7.8 86. ]
 [ 8.3 81. ]]


In [13]:
dataset = pd.read_csv('iris.csv')
dataset.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [14]:
x=dataset.iloc[:,:1].values
y=dataset.iloc[:,:4].values
print("x values",x)
print("y values",y)

x values [[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]
 [6.3]
 [6.1]
 [6.4]
 [6.6]
 [6.8]
 [6.7]
 [6. ]
 [5.7]
 [5.5]
 [5.5]
 [5.8]
 [6. ]
 [5.4]
 [6. ]
 [6.7]
 [6.3]
 [5.6]
 [5.5]
 [5.5]
 [6.1]
 [5.8]
 [5. ]
 [5.6]
 [5.7]
 [5.7]
 [6.2]
 [5.1]
 [5.7]
 [6.3]
 [5.8]
 [7.1]
 [6.3]
 [6.5]
 [7.6]
 [4.9]
 [7.3]
 [6.7]
 [7.2]
 [6.5]
 [6.4]
 [6.8]
 [5.7]
 [5.8]
 [6.4]
 [6.5]
 [7.7]
 [7.7]
 [6. ]
 [6.9]
 [5.6]
 [7.7]
 [6.3]
 [6.7]
 [7.2]
 [6.2]
 [6.1]
 [6.4]
 [7.2]
 [7.4]
 [7.9]
 [6.4]
 [6.3]
 [6.1]
 [7.7]
 [6.3]
 [6.4]
 [6. ]
 [6.9]
 [6.7]
 [6.

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(x_test)

[[6.4]
 [6.3]
 [7. ]
 [6.2]
 [6.7]
 [4.8]
 [5.4]
 [6.5]
 [5.4]
 [5.8]
 [5.6]
 [4.8]
 [5.6]
 [6.3]
 [6.7]
 [5.7]
 [6.4]
 [6.5]
 [5.6]
 [5.8]
 [5. ]
 [6.9]
 [6.8]
 [5.7]
 [5.7]
 [6.5]
 [7.7]
 [5.1]
 [5.8]
 [5.8]
 [6.4]
 [5.1]
 [6.8]
 [4.8]
 [5.7]
 [7.3]
 [4.9]
 [6.2]
 [5.7]
 [5.2]
 [5. ]
 [4.8]
 [7.7]
 [4.9]
 [5.6]]


In [16]:
print(y_test)

[[6.4 3.1 5.5 1.8]
 [6.3 2.5 4.9 1.5]
 [7.  3.2 4.7 1.4]
 [6.2 2.2 4.5 1.5]
 [6.7 2.5 5.8 1.8]
 [4.8 3.4 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [6.5 3.  5.8 2.2]
 [5.4 3.9 1.7 0.4]
 [5.8 2.7 4.1 1. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.  1.4 0.1]
 [5.6 2.9 3.6 1.3]
 [6.3 2.8 5.1 1.5]
 [6.7 3.3 5.7 2.5]
 [5.7 2.8 4.1 1.3]
 [6.4 2.8 5.6 2.2]
 [6.5 3.  5.2 2. ]
 [5.6 2.7 4.2 1.3]
 [5.8 2.7 5.1 1.9]
 [5.  3.5 1.6 0.6]
 [6.9 3.1 5.4 2.1]
 [6.8 3.2 5.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.7 2.5 5.  2. ]
 [6.5 2.8 4.6 1.5]
 [7.7 2.6 6.9 2.3]
 [5.1 3.4 1.5 0.2]
 [5.8 2.7 3.9 1.2]
 [5.8 2.6 4.  1.2]
 [6.4 3.2 5.3 2.3]
 [5.1 3.3 1.7 0.5]
 [6.8 2.8 4.8 1.4]
 [4.8 3.1 1.6 0.2]
 [5.7 4.4 1.5 0.4]
 [7.3 2.9 6.3 1.8]
 [4.9 2.4 3.3 1. ]
 [6.2 2.8 4.8 1.8]
 [5.7 2.6 3.5 1. ]
 [5.2 3.5 1.5 0.2]
 [5.  3.  1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [7.7 3.8 6.7 2.2]
 [4.9 2.5 4.5 1.7]
 [5.6 2.5 3.9 1.1]]
